    echo "Choose lattice type:"
    echo "1. Cubic"
    echo "2. Tetragonal"
    echo "3. Orthorhombic"
    echo "4. Hexagonal"
    echo "5. Monoclinic"
    echo "6. Triclinic"
    read -p "Enter your choice (1–6): " lattice_choice

    # Default values
    a=20.0; b=20.0; c=20.0
    alpha=90.0; beta=90.0; gamma=90.0

    case $lattice_choice in
        1) read -p "Enter lattice parameter a: " a; b=$a; c=$a ;;
        2) read -p "Enter lattice parameter a: " a; read -p "Enter c: " c; b=$a ;;
        3) read -p "Enter a: " a; read -p "Enter b: " b; read -p "Enter c: " c ;;
        4) read -p "Enter a: " a; b=$a; read -p "Enter c: " c; gamma=120.0 ;;
        5) read -p "Enter a: " a; read -p "Enter b: " b; read -p "Enter c: " c; read -p "Enter beta: " beta ;;
        6) read -p "Enter a: " a; read -p "Enter b: " b; read -p "Enter c: " c; \
           read -p "Enter alpha: " alpha; read -p "Enter beta: " beta; read -p "Enter gamma: " gamma ;;
        *) echo "Invalid choice. Using default cubic parameters." ;;
    esac

    read -p "Enter space group name (e.g. P1, P2_1/c, Fm-3m): " space_group

    echo "Enter atomic positions (format: Symbol x y z), one per line."
    echo "Type 'done' to finish input."
    atom_lines=()
    while true; do
        read -p "> " line
        [[ "$line" == "done" ]] && break
        atom_lines+=("$line")
    done

    OUTPUT_FILE="cif_template_custom.cif"
    cat > "$OUTPUT_FILE" << EOF
#======================================================================
# CRYSTAL DATA GENERATED BY qei.sh
#----------------------------------------------------------------------
data_VESTA_phase_1

_cell_length_a                         $a
_cell_length_b                         $b
_cell_length_c                         $c
_cell_angle_alpha                      $alpha
_cell_angle_beta                       $beta
_cell_angle_gamma                      $gamma
_space_group_name_H-M_alt              '$space_group'

loop_
   _atom_site_type_symbol
   _atom_site_fract_x
   _atom_site_fract_y
   _atom_site_fract_z
   _atom_site_occupancy
EOF

    for atom in "${atom_lines[@]}"; do
        symbol=$(echo "$atom" | awk '{print $1}')
        x=$(echo "$atom" | awk '{print $2}')
        y=$(echo "$atom" | awk '{print $3}')
        z=$(echo "$atom" | awk '{print $4}')
        printf "   %-4s     %9s     %9s     %9s     1.000\n" "$symbol" "$x" "$y" "$z" >> "$OUTPUT_FILE"
    done

    echo "Customized CIF template with atom positions created: $OUTPUT_FILE"
