@echo off
setlocal enabledelayedexpansion

echo Choose lattice type:
echo 1. Cubic
echo 2. Tetragonal
echo 3. Orthorhombic
echo 4. Hexagonal
echo 5. Monoclinic
echo 6. Triclinic
set /p lattice_choice="Enter your choice (1–6): "

:: Default values
set a=20.0
set b=20.0
set c=20.0
set alpha=90.0
set beta=90.0
set gamma=90.0

if "%lattice_choice%"=="1" (
    set /p a="Enter lattice parameter a: "
    set b=!a!
    set c=!a!
) else if "%lattice_choice%"=="2" (
    set /p a="Enter lattice parameter a: "
    set /p c="Enter lattice parameter c: "
    set b=!a!
) else if "%lattice_choice%"=="3" (
    set /p a="Enter a: "
    set /p b="Enter b: "
    set /p c="Enter c: "
) else if "%lattice_choice%"=="4" (
    set /p a="Enter a: "
    set b=!a!
    set /p c="Enter c: "
    set gamma=120.0
) else if "%lattice_choice%"=="5" (
    set /p a="Enter a: "
    set /p b="Enter b: "
    set /p c="Enter c: "
    set /p beta="Enter angle beta (≠90): "
) else if "%lattice_choice%"=="6" (
    set /p a="Enter a: "
    set /p b="Enter b: "
    set /p c="Enter c: "
    set /p alpha="Enter angle alpha: "
    set /p beta="Enter angle beta: "
    set /p gamma="Enter angle gamma: "
)

set /p space_group="Enter space group name (e.g. P1, P2_1/c, Fm-3m): "

REM === Ask user for output CIF filename ===
echo.
echo Enter the name (or full path) for the CIF file to save:
echo (Example: my_structure.cif or C:\Users\YourName\Desktop\sample.cif)
set /p outfile="Output CIF file name: "

(
echo #======================================================================
echo # CRYSTAL DATA GENERATED BY cifgenerator.bat
echo #----------------------------------------------------------------------
echo data_VESTA_phase_1
echo.
echo _cell_length_a                         !a!
echo _cell_length_b                         !b!
echo _cell_length_c                         !c!
echo _cell_angle_alpha                      !alpha!
echo _cell_angle_beta                       !beta!
echo _cell_angle_gamma                      !gamma!
echo _space_group_name_H-M_alt              '!space_group!'
echo.
echo loop_
echo    _atom_site_type_symbol
echo    _atom_site_fract_x
echo    _atom_site_fract_y
echo    _atom_site_fract_z
echo    _atom_site_occupancy
) > %outfile%

echo Please provide the path to the atomic positions text file.
echo (Tip: You can drag and drop the file into this window and press Enter.)
set /p positions_file="Positions file path: "

REM Append rows to CIF, skipping blank lines and lines starting with # or ;
for /f "usebackq tokens=1-5" %%A in (`findstr /R /V "^[;#]" "%positions_file%" ^| findstr /R /V "^$"`) do (
    REM If occupancy is missing, default to 1.0
    set "occ=%%E"
    if "!occ!"=="" set "occ=1.0"
    >> "%outfile%" echo %%A  %%B  %%C  %%D  !occ!
)


echo.
echo  CIF written successfully: "%outfile%"
pause