@echo off
setlocal enabledelayedexpansion

echo Choose lattice type:
echo 1. Cubic
echo 2. Tetragonal
echo 3. Orthorhombic
echo 4. Hexagonal
echo 5. Monoclinic
echo 6. Triclinic
set /p lattice_choice="Enter your choice (1¨C6): "

:: Default values
set a=20.0
set b=20.0
set c=20.0
set alpha=90.0
set beta=90.0
set gamma=90.0

if "%lattice_choice%"=="1" (
    set /p a="Enter lattice parameter a: "
    set b=!a!
    set c=!a!
) else if "%lattice_choice%"=="2" (
    set /p a="Enter lattice parameter a: "
    set /p c="Enter lattice parameter c: "
    set b=!a!
) else if "%lattice_choice%"=="3" (
    set /p a="Enter a: "
    set /p b="Enter b: "
    set /p c="Enter c: "
) else if "%lattice_choice%"=="4" (
    set /p a="Enter a: "
    set b=!a!
    set /p c="Enter c: "
    set gamma=120.0
) else if "%lattice_choice%"=="5" (
    set /p a="Enter a: "
    set /p b="Enter b: "
    set /p c="Enter c: "
    set /p beta="Enter angle beta (¡Ù90): "
) else if "%lattice_choice%"=="6" (
    set /p a="Enter a: "
    set /p b="Enter b: "
    set /p c="Enter c: "
    set /p alpha="Enter angle alpha: "
    set /p beta="Enter angle beta: "
    set /p gamma="Enter angle gamma: "
)

set /p space_group="Enter space group name (e.g. P1, P2_1/c, Fm-3m): "

:: Collect atom data
set "tempfile=_atoms.tmp"
break > %tempfile%
echo Enter atomic positions (Symbol x y z), one per line. Type 'done' to finish.

:read_atoms
set /p atom="> "
if "%atom%"=="done" goto write_file
echo %atom%>> %tempfile%
goto read_atoms

:write_file
set "outfile=qe_template_custom.cif"
(
echo #======================================================================
echo # CRYSTAL DATA GENERATED BY cifgenerator.bat
echo #----------------------------------------------------------------------
echo data_VESTA_phase_1
echo.
echo _cell_length_a                         !a!
echo _cell_length_b                         !b!
echo _cell_length_c                         !c!
echo _cell_angle_alpha                      !alpha!
echo _cell_angle_beta                       !beta!
echo _cell_angle_gamma                      !gamma!
echo _space_group_name_H-M_alt              '!space_group!'
echo.
echo loop_
echo    _atom_site_type_symbol
echo    _atom_site_fract_x
echo    _atom_site_fract_y
echo    _atom_site_fract_z
echo    _atom_site_occupancy
) > %outfile%

:: Append atoms using formatted PowerShell output
for /f "tokens=1,2,3,4" %%a in (%tempfile%) do (
    powershell -Command "('{0,-4}  {1,10:F5}  {2,10:F5}  {3,10:F5}  1.000' -f '%%a','%%b','%%c','%%d')" >> %outfile%
)

del %tempfile%
echo.
echo CIF file generated: %outfile%
pause
